# Commands to start on workspace startup
tasks:
  - init: sudo rustup target add wasm32-unknown-unknown && sudo cargo install trunk
    command: sudo rustup target add wasm32-unknown-unknown && sudo cargo install trunk

