# Commands to start on workspace startup
tasks:
  - init: rustup target add wasm32-unknown-unknown && cargo install trunk
    command: rustup target add wasm32-unknown-unknown && cargo install trunk

